'use client'

import { useState } from 'react'
import { ArrowUpRight, Download, LibraryBig, Search, SlidersHorizontal, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription } from '@/components/ui/empty'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field'
import { downloadFile, translationLocale, type Manuscript, type TranslationLanguage } from '@/lib/manuscripts'
import { TranslationLanguageSelect } from '@/components/translation-language-select'

export function ManuscriptLibrary({ items, personal = false, translations = false, onOpen, onDelete, onDecode }: { items: Manuscript[]; personal?: boolean; translations?: boolean; onOpen: (item: Manuscript) => void; onDelete: (id: string) => void; onDecode: () => void }) {
  const [outputLanguage, setOutputLanguage] = useState<TranslationLanguage>('English')
  const locale = translationLocale(outputLanguage)
  const [search, setSearch] = useState('')
  const [script, setScript] = useState('All scripts')
  const [subject, setSubject] = useState('All subjects')
  const [period, setPeriod] = useState('All periods')
  const [language, setLanguage] = useState('All languages')
  const [location, setLocation] = useState('All locations')
  const [confidence, setConfidence] = useState('Any confidence')
  const [filters, setFilters] = useState(false)
  const [deleting, setDeleting] = useState<Manuscript | null>(null)
  const results = items.filter(item => `${item.title} ${item.script} ${item.subject} ${item.language} ${item.location} ${item.text}`.toLowerCase().includes(search.toLowerCase()) && (script === 'All scripts' || item.script === script) && (subject === 'All subjects' || item.subject === subject) && (period === 'All periods' || item.period === period) && (language === 'All languages' || item.language === language) && (location === 'All locations' || item.location === location) && (confidence === 'Any confidence' || item.confidence >= Number(confidence)))
  function reset() { setSearch(''); setScript('All scripts'); setSubject('All subjects'); setPeriod('All periods'); setLanguage('All languages'); setLocation('All locations'); setConfidence('Any confidence') }
  return <div className="flex flex-col gap-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{personal ? 'Your discoveries, together' : 'A shared cultural legacy'}</p><h1 className="mt-3 font-serif text-4xl font-medium">{translations ? 'Across languages.' : personal ? 'My manuscripts.' : 'The digital archive.'}</h1><p className="mt-3 max-w-xl text-sm leading-7 text-muted-foreground">{personal ? 'Your session collection. Export your work before refreshing — this demo does not store files permanently.' : 'A curated, illustrative collection of Indian manuscripts. Explore the scripts, stories, and knowledge within.'}</p></div><Button onClick={onDecode} className="h-10 px-4">Decode a manuscript<ArrowUpRight data-icon="inline-end" /></Button></div>
    {translations && <TranslationLanguageSelect value={outputLanguage} onChange={setOutputLanguage} />}
    <div className="flex flex-col gap-4"><div className="flex flex-wrap items-center gap-3"><div className="relative min-w-48 flex-1"><Search className="absolute top-3.5 left-4 size-4 text-muted-foreground" /><input aria-label="Search manuscripts" placeholder="Search manuscripts, keywords, subjects…" value={search} onChange={e => setSearch(e.target.value)} className="h-11 w-full pr-4 pl-11 text-sm" /></div><select aria-label="Filter by script" value={script} onChange={e => setScript(e.target.value)} className="h-11 px-4 text-sm">{['All scripts', 'Devanagari', 'Tamil', 'Bengali'].map(value => <option key={value}>{value}</option>)}</select><Button variant="outline" className="h-11 px-4" onClick={() => setFilters(!filters)} aria-expanded={filters}><SlidersHorizontal data-icon="inline-start" />Filters</Button></div>
    {filters && <div className="panel p-5"><FieldGroup className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[{ label: 'Subject', value: subject, set: setSubject, options: ['All subjects', ...new Set(items.map(i => i.subject))] }, { label: 'Period', value: period, set: setPeriod, options: ['All periods', ...new Set(items.map(i => i.period))] }, { label: 'Language', value: language, set: setLanguage, options: ['All languages', ...new Set(items.map(i => i.language))] }, { label: 'Location', value: location, set: setLocation, options: ['All locations', ...new Set(items.map(i => i.location))] }, { label: 'Min. sample confidence', value: confidence, set: setConfidence, options: ['Any confidence', '90', '94', '96'] }].map(filter => <Field key={filter.label}><FieldLabel htmlFor={`filter-${filter.label}`}>{filter.label}</FieldLabel><select id={`filter-${filter.label}`} className="h-10 min-w-0 px-3 text-sm" value={filter.value} onChange={e => filter.set(e.target.value)}>{filter.options.map(option => <option key={option}>{option}</option>)}</select></Field>)}</FieldGroup></div>}
    <div className="flex items-center justify-between"><p className="text-xs text-muted-foreground">{results.length} manuscript{results.length !== 1 && 's'} · {personal ? 'Saved in this session' : 'Illustrative collection'}</p><button onClick={reset} className="text-xs text-primary">Reset filters</button></div></div>
    {results.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{results.map(item => <Card key={item.id} className="archive-card"><div className="relative h-48 overflow-hidden"><img src={item.image} alt={`${item.script} manuscript: ${item.title}`} loading="lazy" className="archival-image size-full object-cover" /><span className="absolute top-3 left-3"><Badge variant="secondary">{item.script}</Badge></span></div><CardHeader><CardTitle>{item.title}</CardTitle><CardDescription>{item.subject} · {item.period}</CardDescription></CardHeader><CardContent><p lang={translations ? locale.code : undefined} dir={translations ? locale.direction : undefined} className="text-sm leading-6 text-muted-foreground">{translations ? item.translations[outputLanguage] : `${item.language} · ${item.location}`}</p><p className="mt-3 text-xs text-muted-foreground">{personal ? 'Saved' : 'Demo record'} · {item.date} · {item.confidence}% sample confidence</p></CardContent><CardFooter className="justify-between"><Button variant="ghost" onClick={() => onOpen(translations ? { ...item, preferredTranslation: outputLanguage } : item)}>View & edit<ArrowUpRight data-icon="inline-end" /></Button><div className="flex gap-1"><Button variant="ghost" size="icon" aria-label={`Download ${translations ? outputLanguage + ' translation of ' : ''}${item.title}`} onClick={() => downloadFile(translations ? item.translations[outputLanguage] : item.text, translations ? `script-decipher-${item.script.toLowerCase()}-${locale.code}-translation.txt` : `${item.script.toLowerCase()}-transcription.txt`)}><Download /></Button>{personal && <Button variant="ghost" size="icon" aria-label={`Delete ${item.title}`} onClick={() => setDeleting(item)}><Trash2 /></Button>}</div></CardFooter></Card>)}</div> : <Empty className="min-h-72 border"><EmptyHeader><EmptyMedia variant="icon"><LibraryBig /></EmptyMedia><EmptyTitle>{items.length ? 'No matching manuscripts' : 'Your first discovery is waiting'}</EmptyTitle><EmptyDescription>{items.length ? 'Try another keyword or remove a filter.' : 'Decode a sample or upload an image, then save the result to your session collection.'}</EmptyDescription></EmptyHeader><Button onClick={items.length ? reset : onDecode}>{items.length ? 'Clear filters' : 'Decode a manuscript'}</Button></Empty>}
    <Dialog open={!!deleting} onOpenChange={open => { if (!open) setDeleting(null) }}><DialogContent><DialogHeader><DialogTitle>Remove this manuscript?</DialogTitle><DialogDescription>{deleting?.title} will be removed from your session collection. Export any edits first. This cannot be undone.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleting(null)}>Keep manuscript</Button><Button onClick={() => { if (deleting) onDelete(deleting.id); setDeleting(null) }}>Remove manuscript</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
