'use client'

import { useEffect, useState } from 'react'
import { MotionConfig } from 'framer-motion'
import { ArrowLeft, ArrowRight, ArrowUpRight, Bell, BookOpen, ChartNoAxesColumn, ChevronRight, CircleHelp, Globe2, Home, Info, LibraryBig, Menu, Moon, ScanLine, Settings2, Sparkles, Sun, UserRound, X } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Toaster } from '@/components/ui/sonner'
import { Switch } from '@/components/ui/switch'
import { Field, FieldContent, FieldDescription, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { LandingPage, Brand } from '@/components/landing-page'
import { DecoderWorkspace } from '@/components/decoder-workspace'
import { ManuscriptLibrary } from '@/components/manuscript-library'
import { manuscripts, type Manuscript } from '@/lib/manuscripts'
import { cn } from '@/lib/utils'

type View = 'home' | 'dashboard' | 'decode' | 'library' | 'saved' | 'translations' | 'analytics' | 'settings'
const navigation = [{ id: 'dashboard', label: 'Dashboard', icon: Home }, { id: 'saved', label: 'My manuscripts', icon: BookOpen }, { id: 'decode', label: 'Decode', icon: ScanLine }, { id: 'translations', label: 'Translations', icon: Globe2 }, { id: 'library', label: 'Explore archive', icon: LibraryBig }, { id: 'analytics', label: 'Analytics', icon: ChartNoAxesColumn }, { id: 'settings', label: 'Settings', icon: Settings2 }] as const

export function ManuscriptApp() {
  const [view, setView] = useState<View>('home')
  const [sample, setSample] = useState<Manuscript>()
  const [initialComplete, setInitialComplete] = useState(false)
  const [workspaceKey, setWorkspaceKey] = useState(0)
  const [saved, setSaved] = useState<Manuscript[]>([])
  const [about, setAbout] = useState(false)
  const [mobileMenu, setMobileMenu] = useState(false)
  const [light, setLight] = useState(false)
  const [contrast, setContrast] = useState(false)
  const [large, setLarge] = useState(false)
  const [notifications, setNotifications] = useState(false)
  useEffect(() => { document.documentElement.classList.toggle('light', light); document.documentElement.classList.toggle('high-contrast', contrast); document.documentElement.classList.toggle('large-text', large) }, [light, contrast, large])
  function navigate(next: View) { setView(next); setMobileMenu(false); window.scrollTo({ top: 0, behavior: 'instant' }) }
  function openDecoder(item?: Manuscript, complete = false) { setSample(item); setInitialComplete(complete); setWorkspaceKey(key => key + 1); navigate('decode') }
  function save(item: Manuscript) { setSaved(previous => [...previous.filter(entry => entry.id !== item.id), { ...item, translations: { ...item.translations } }]); toast.success('Saved to your session collection', { description: 'Export your work before refreshing. Permanent storage is not connected.' }) }
  const words = saved.reduce((sum, item) => sum + item.text.trim().split(/\s+/u).filter(Boolean).length, 0)
  return <MotionConfig reducedMotion="user"><a href="#main-content" className="sr-only fixed top-2 left-2 z-50 rounded-lg bg-primary px-4 py-3 text-primary-foreground focus:not-sr-only">Skip to content</a>
    {view === 'home' ? <LandingPage onDecode={() => openDecoder()} onExplore={() => navigate('library')} onSample={item => openDecoder(item)} onAbout={() => setAbout(true)} /> : <div className="min-h-screen">
      {mobileMenu && <button aria-label="Close navigation overlay" onClick={() => setMobileMenu(false)} className="fixed inset-0 z-30 bg-background/80 backdrop-blur-sm lg:hidden" />}
      <aside className={cn('no-print fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r border-border bg-card transition-transform lg:translate-x-0', mobileMenu ? 'translate-x-0' : '-translate-x-full')}>
        <div className="flex h-24 items-center justify-between border-b border-border px-5"><button onClick={() => navigate('home')}><span className="flex items-center gap-2.5"><BookOpen className="size-6 text-primary" strokeWidth={1.5} /><span className="text-left font-serif text-xl font-semibold leading-[1.1]">Script<br /><span className="text-primary">Decipher</span></span></span></button><Button variant="ghost" size="icon" onClick={() => setMobileMenu(false)} aria-label="Close navigation" className="lg:hidden"><X /></Button></div>
        <div className="px-5 pt-7 text-[10px] tracking-[.18em] text-muted-foreground uppercase">Your research space</div>
        <nav aria-label="Workspace navigation" className="mt-4 flex flex-col gap-1 px-3">{navigation.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => navigate(id)} aria-current={view === id ? 'page' : undefined} className={cn('flex h-11 items-center gap-3 rounded-lg px-3 text-sm transition-colors', view === id ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-secondary hover:text-foreground')}><Icon className="size-[18px]" strokeWidth={1.6} />{label}{id === 'saved' && saved.length > 0 && <span className="ml-auto text-xs">{saved.length}</span>}{view === id && <ChevronRight className="ml-auto size-3.5" />}</button>)}</nav>
        <div className="mx-4 mt-auto rounded-xl border border-primary/20 bg-primary/5 p-4"><Sparkles className="size-5 text-primary" /><p className="mt-3 font-serif text-lg">A bridge across centuries.</p><p className="mt-2 text-xs leading-6 text-muted-foreground">Explore the full workflow in this interactive research demo.</p><button onClick={() => setAbout(true)} className="mt-3 flex items-center gap-2 text-xs text-primary">About the prototype<ArrowUpRight className="size-3" /></button></div>
        <div className="mt-5 flex items-center gap-3 border-t border-border p-5"><span className="flex size-9 items-center justify-center rounded-full border border-border bg-secondary text-primary"><UserRound className="size-4" /></span><div><p className="text-sm">Guest researcher</p><p className="mt-1 text-[11px] text-muted-foreground">Demo session · No account</p></div></div>
      </aside>
      <div className="print-workspace lg:pl-64"><header className="no-print flex h-24 items-center justify-between border-b border-border px-5 md:px-8"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" aria-label="Open workspace navigation" onClick={() => setMobileMenu(true)} className="lg:hidden"><Menu /></Button><button onClick={() => navigate('home')} className="hidden items-center gap-2 text-xs text-muted-foreground hover:text-primary sm:flex"><ArrowLeft className="size-3.5" />Back to home</button><span className="hidden text-muted-foreground/40 sm:inline">/</span><span className="text-sm">{navigation.find(n => n.id === view)?.label}</span></div><div className="flex items-center gap-3"><Badge variant="outline">Demo workspace</Badge><Button variant="ghost" size="icon" aria-label={light ? 'Use dark mode' : 'Use light mode'} onClick={() => setLight(!light)}>{light ? <Moon /> : <Sun />}</Button><Button variant="ghost" size="icon" aria-label="View notifications" onClick={() => setNotifications(true)}><Bell /></Button></div></header>
        <main id="main-content" className="print-workspace mx-auto max-w-[1600px] px-5 py-8 pb-24 md:px-8 lg:pb-12">
          {view === 'dashboard' && <div className="flex flex-col gap-8"><div><p className="eyebrow">Welcome, curious mind</p><h1 className="mt-3 font-serif text-4xl font-medium">Your next discovery awaits.</h1><p className="mt-3 text-sm text-muted-foreground">Digitize and preserve ancient knowledge, one page at a time.</p></div><div className="grid gap-4 sm:grid-cols-3">{[{ label: 'Session manuscripts', value: saved.length }, { label: 'Words preserved', value: words }, { label: 'Scripts to explore', value: 3 }].map(stat => <div key={stat.label} className="panel p-6"><p className="text-sm text-muted-foreground">{stat.label}</p><p className="mt-3 font-serif text-4xl text-primary">{stat.value}</p></div>)}</div><div className="grid overflow-hidden rounded-xl border border-primary/20 bg-card md:grid-cols-2"><div className="flex flex-col items-start gap-5 p-8"><ScanLine className="size-7 text-primary" /><h2 className="font-serif text-3xl">Give old words a new life.</h2><p className="text-sm leading-7 text-muted-foreground">Upload a manuscript or try a curated sample. Experience the journey from handwritten page to editable, translated text.</p><Button className="h-11 px-5" onClick={() => openDecoder()}>Start decoding<ArrowRight data-icon="inline-end" /></Button></div><img src="/images/sanskrit-manuscript.png" alt="Antique Sanskrit manuscript" className="h-64 w-full object-cover md:h-full" /></div><div><div className="mb-5 flex items-center justify-between"><h2 className="font-serif text-2xl">A collection to spark your curiosity</h2><button onClick={() => navigate('library')} className="text-xs text-primary">Explore all<ArrowUpRight className="ml-1 inline size-3" /></button></div><div className="grid gap-4 md:grid-cols-3">{manuscripts.map(item => <button onClick={() => openDecoder(item)} key={item.id} className="panel flex items-center gap-4 p-3 text-left hover:border-primary/30"><img src={item.image} alt={item.script + ' sample manuscript'} className="size-16 rounded-lg object-cover" /><div><p className="text-sm">{item.title}</p><p className="mt-2 text-xs text-muted-foreground">{item.script} · Demo</p></div></button>)}</div></div></div>}
          <div hidden={view !== 'decode'}><DecoderWorkspace key={workspaceKey} initial={sample} initialComplete={initialComplete} onSave={save} /></div>
          {(view === 'library' || view === 'saved' || view === 'translations') && <ManuscriptLibrary key={view} items={view === 'library' ? manuscripts : saved} personal={view !== 'library'} translations={view === 'translations'} onOpen={item => openDecoder(item, true)} onDecode={() => openDecoder()} onDelete={id => { setSaved(previous => previous.filter(item => item.id !== id)); toast.success('Removed from the session collection') }} />}
          {view === 'analytics' && <div className="flex flex-col gap-7"><div><p className="eyebrow">Your preservation footprint</p><h1 className="mt-3 font-serif text-4xl">Session insights.</h1><p className="mt-3 text-sm text-muted-foreground">Activity from this browser session only. Sample confidence values are not accuracy measurements.</p></div><div className="grid gap-4 sm:grid-cols-3">{[['Manuscripts saved', saved.length], ['Words in your collection', words], ['Languages represented', new Set(saved.map(item => item.language)).size]].map(([label, value]) => <div key={label} className="panel p-6"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-4 font-serif text-5xl text-primary">{value}</p></div>)}</div><section className="panel overflow-hidden"><h2 className="panel-heading">Your collection by script</h2><table className="w-full text-left text-sm"><thead><tr className="border-b border-border text-muted-foreground"><th className="p-5 font-normal">Script</th><th className="p-5 font-normal">Saved manuscripts</th><th className="p-5 font-normal">Words</th></tr></thead><tbody>{['Devanagari', 'Tamil', 'Bengali'].map(script => <tr key={script} className="border-b border-border last:border-0"><td className="p-5">{script}</td><td className="p-5">{saved.filter(item => item.script === script).length}</td><td className="p-5">{saved.filter(item => item.script === script).reduce((sum, item) => sum + item.text.trim().split(/\s+/).filter(Boolean).length, 0)}</td></tr>)}</tbody></table></section></div>}
          {view === 'settings' && <div className="flex max-w-3xl flex-col gap-8"><div><p className="eyebrow">A space that feels like yours</p><h1 className="mt-3 font-serif text-4xl">Reading preferences.</h1><p className="mt-3 text-sm text-muted-foreground">Make the workspace comfortable for your eyes and your workflow.</p></div><section className="panel overflow-hidden"><h2 className="panel-heading">Appearance & accessibility</h2><div className="p-6"><FieldGroup>{[{ id: 'light-mode', label: 'Light mode', description: 'A warm parchment canvas for daytime reading.', value: light, set: setLight }, { id: 'high-contrast', label: 'High contrast', description: 'Increase text and border contrast across the app.', value: contrast, set: setContrast }, { id: 'large-text', label: 'Larger text', description: 'Increase the reading size throughout your workspace.', value: large, set: setLarge }].map(setting => <Field orientation="horizontal" key={setting.id}><FieldContent><FieldLabel htmlFor={setting.id}>{setting.label}</FieldLabel><FieldDescription>{setting.description}</FieldDescription></FieldContent><Switch id={setting.id} checked={setting.value} onCheckedChange={setting.set} /></Field>)}</FieldGroup></div></section><section className="panel p-6"><h2 className="flex items-center gap-2 text-sm font-medium"><Info className="size-4 text-primary" />About your session</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">No sign-in is required. Uploaded images and edited results remain in memory in this browser tab; they are not uploaded to a server. Refreshing clears your collection and preferences. Export your work to keep it.</p></section></div>}
        </main>
      </div>
      <nav aria-label="Mobile quick navigation" className="no-print fixed inset-x-0 bottom-0 z-20 flex justify-around border-t border-border bg-card/95 px-2 py-3 backdrop-blur-md lg:hidden">{navigation.filter(item => ['dashboard', 'decode', 'saved', 'settings'].includes(item.id)).map(({ id, label, icon: Icon }) => <button key={id} onClick={() => navigate(id)} className={cn('flex min-w-16 flex-col items-center gap-1.5 text-[10px]', view === id ? 'text-primary' : 'text-muted-foreground')}><Icon className="size-5" />{label}</button>)}</nav>
    </div>}
    <Dialog open={about} onOpenChange={setAbout}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Ancient wisdom. Reimagined.</DialogTitle><DialogDescription>Script Decipher is an interactive research prototype exploring how AI could help preserve India&apos;s handwritten heritage.</DialogDescription></DialogHeader><div className="flex flex-col gap-4 text-sm leading-7 text-muted-foreground"><p>Try image uploads, preview enhancement, editable Unicode texts, translations, and exports across Devanagari, Tamil, and Bengali sample collections.</p><p>This version uses fixed demo results and AI-generated manuscript images. It does not run TrOCR, IndicTrans2, Bhashini, or historical dating. Outputs are illustrative and should not be used as research evidence.</p><p>Your collection lasts only for this browser session. A production version would need validated OCR models, a Python processing service, authentication, and permanent archival storage.</p></div><Button onClick={() => { setAbout(false); openDecoder() }} className="h-11">Explore the prototype<ArrowRight data-icon="inline-end" /></Button></DialogContent></Dialog>
    <Dialog open={notifications} onOpenChange={setNotifications}><DialogContent><DialogHeader><DialogTitle>You&apos;re all caught up.</DialogTitle><DialogDescription>No new notifications. Your session collection contains {saved.length} manuscript{saved.length !== 1 && 's'}. Remember to export your discoveries before refreshing.</DialogDescription></DialogHeader></DialogContent></Dialog>
    <Toaster position="bottom-right" theme={light ? 'light' : 'dark'} />
  </MotionConfig>
}
